title: WGH Homepage  
url: "https://cheuerde.github.io"  
baseurl: "/awgh_homepage"  
remote_theme: mmistakes/minimal-mistakes  
repository: cheuerde/wgh_homepage  
permalink: /:categories/:title/  
author:  
  name: Your Name  
  email: your@email.com  
  twitter: your_twitter  
  github: your_github  
  linkedin: your_linkedin  
  
navigation:  
  - title: Info  
    url: /info/  
  - title: Garden  
    url: /garden/  
  - title: Community  
    url: /community/  
 
