title: My Gardening Community  
description: A place for gardening enthusiasts to share tips, tricks, and advice.  
baseurl: ""  
url: "https://cheuerde.github.io"  
timezone: "America/New_York"  
theme: minima  
