title: WGH Homepage  
url: "https://cheuerde.github.io"  
baseurl: "/wgh_homepage"  
remote_theme: mmistakes/minimal-mistakes  
repository: cheuerde/wgh_homepage  
permalink: /:categories/:title/  
plugins:  
  - jekyll-include-cache 
author:  
  name: Your Name  
  email: your@email.com  
  twitter: your_twitter  
  github: your_github  
  linkedin: your_linkedin  
  
defaults:  
  - scope:  
      path: ""  
      type: "pages"  
    values:  
      layout: "single"  
      author_profile: false  
      read_time: false  
      comments: false  
      share: false  
      related: false  
      sidebar:  
        nav: "sidebar-navigation"  

  
navigation:  
  - title: Info  
    url: /info/  
  - title: Garden  
    url: /garden/  
  - title: Community  
    url: /community/  
 
