title: Your Site Title  
description: A description of your site  
author:  
  name: Your Name  
  
remote_theme: mmistakes/minimal-mistakes  
  
plugins:  
  - jekyll-remote-theme  
  - jekyll-include-cache  
  
# Add the following lines if you want to enable Google Analytics tracking  
# Replace "UA-XXXXX-Y" with your own tracking ID  
#google_analytics: "UA-XXXXX-Y"  
  
# Author information for the sidebar  
author:  
  name: Your Name  
  avatar: "/path/to/your/avatar.jpg"  
  bio: "A short bio about you or your website."  
  location: "City, Country"  
  links:  
    - label: "Info"  
      icon: "fas fa-fw fa-info-circle"  
      url: "/info"  
    - label: "Gardening Tips"  
      icon: "fas fa-fw fa-seedling"  
      url: "/gardening-tips"  
    - label: "Our Gardening Community"  
      icon: "fas fa-fw fa-users"  
      url: "/our-gardening-community"  
  
# Enable the following line to enforce HTTPS on your site  
#enforce_ssl: your-username.github.io  

